CREATE TABLE ARTIST
(
    ID          bigint NOT NULL,
    ARTIST_NAME varchar(255) NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE ARTIST_ID_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1 CACHE 1
;

