services:
  postgres:
    image: postgres:12.2
    hostname: postgres
    container_name: test-artist-records
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    ports:
      - "${TEST_POSTGRES_PORT}:5432"
    volumes:
      - test-music-records-data:/var/lib/postgresql/data
    networks:
      - test-music-records-net

volumes:
  test-music-records-data:

networks:
  test-music-records-net:
    driver: bridge
